# Makefile for/für ``Morsemann'' - PortAudio
#
# Available targets/Verfügbare ``Targets'':
#   all, allusers, clean, clean-dist
#
# Prerequisites for compiling:
#   make, ncurses-dev, portaudio19-dev
#

# Your favourite C++ compiler/Ihr C++-Kompiler
CXX	= g++

# Select your curses lib
#CURSESLIB = -lcurses
CURSESLIB = -lncurses

# Uncomment next line if your curses terminal does not
# properly support colors...
# CXXFLAGS += -DNO_COLORS

CXXFLAGS += -DHAVE_PORTAUDIO -g -O2 -Wall -Wextra
SOUNDLIBS = -lportaudio

#
# You shouldn't have to edit something below here!!!
# Ab dieser Zeile bitte nichts mehr ändern!!!
#

include Makefile.common
